version: '3'

services:
  api:
    build: .
    image: api-marvel-dev:latest
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "5000:80"
    environment:
      - AM_TS=${AM_TS}
      - AM_KEY=${AM_KEY}
      - AM_HASH=${AM_HASH}
      - FCM_KEY_SERVER=${FCM_KEY_SERVER}
    volumes:
      - ./app:/app