name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and tag image
        run: docker build -f Dockerfile -t "docker.pkg.github.com/$GITHUB_REPOSITORY/api-marvel:latest" .
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
      - name: Publish to GPR
        run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/api-marvel:latest"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: cd traefik-website/ && docker-compose pull api_marvel && docker-compose up -d api_marvel
